### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by altanh** [altanh/fractals#1]
Once again it has come to this point.  Although the rewritten code is indeed far cleaner than the code before, it has become somewhat cluttered and static.

**TODO**:
- [ ] Object oriented code
- [ ] Organize into multiple files
- [ ] Generalize fractal system, allow for different equations
- [ ] Allow reading from config files - no need to recompile every time for different params.
- [ ] Others.
